//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace stokTakipUygulamasi.Models.Entity
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.Web.Mvc;
    using System.Xml.Linq;

    public partial class Urunler
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Urunler()
        {
            this.Satislar = new HashSet<Satislar>();
            this.MarkalarListesi = new List<SelectListItem>();
            MarkalarListesi.Insert(0, new SelectListItem { Text = "Önce Kategori Seçilmelidir.", Value = "" });
        }

        public int id { get; set; }
        [Required(ErrorMessage = "Barkod No alaný boþ geçilemez.")]

        public string BarkodNO { get; set; }
        [Required(ErrorMessage = "Kategori alaný boþ geçilemez.")]
        public int KategoriID { get; set; }
        [Required(ErrorMessage = "Marka alaný boþ geçilemez.")]
        public int MarkaID { get; set; }
        [Required(ErrorMessage = "Ürün Adý alaný boþ geçilemez.")]
        [Display(Name = "Ürün Adý")]
        public string UrunAdi { get; set; }
        [Required(ErrorMessage = "Stok alaný boþ geçilemez.")]

        public int UrunStok { get; set; }
        [Required(ErrorMessage = "Ürün Fiyatý alaný boþ geçilemez.")]
        [Display(Name = "Ürün Fiyatý")]
        public double AlisFiyati { get; set; }
        [DataType(DataType.Date)]
        [Required(ErrorMessage = "Tarih alaný boþ geçilemez.")]

        public System.DateTime Tarih { get; set; }
        [Required(ErrorMessage = "Açýklama alaný boþ geçilemez.")]

        public string Aciklama { get; set; }

        public virtual Kategoriler Kategoriler { get; set; }
        public virtual Markalar Markalar { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Satislar> Satislar { get; set; }

        public List<SelectListItem> KategoriListesi { get; set; }

        public List<SelectListItem> MarkalarListesi { get; set; }
        public virtual ICollection<Sepet> Sepet { get; set; }
    }
}
